feat(dotfiles): update install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,51 +10,67 @@ LOG_LEVEL=2
 GITHUB_DOWNLOAD=https://github.com/Watt3r/dotfiles.git
 INSTALL_DIR=~/.dotfiles
 
-tmpdir=$(mktemp -d)
-trap 'rm -rf ${tmpdir}' EXIT
-
 usage() {
 	this="$1"
 	cat <<EOF
-${this}: download Lucas Oberwager's dotfiles
+${this}: Download Lucas Oberwager's dotfiles
 
-Usage: ${this} [-i installdir] [-d]
-  -i sets the installation directory, default is ${INSTALL_DIR}.
-  -d enables debug logging.
+Usage: ${this} [-i installdir] [-l] [-h]
+  -i  Set the installation directory (default is ${INSTALL_DIR}).
+  -l  Set the log level (default is ${LOG_LEVEL}).
+  -h  Show this help message.
 EOF
 	exit 2
 }
 
-main() {
-  parse_args "$@"
+check_command() {
+    command -v "$1" > /dev/null 2>&1 || { echo >&2 "$1 is required but it's not installed. Aborting."; exit 1; }
+}
 
-  # Don't install on root
-  if [ "$(whoami)" == "root" ]; then
-    log_crit "Install should not be run as root. Dotfiles should be installed on a specific user on the system"
-    exit 1
+get_remote_url() {
+    git -C "$1" config --get remote.origin.url
+}
+
+check_repo() {
+  remote_url=$(get_remote_url "$1")
+  if [ "$remote_url" == "$GITHUB_DOWNLOAD" ]; then
+      log_info "'$1' is a proper dotfiles repo."
+  else
+      log_info "'$1' is not a proper dotfiles repo."
   fi
+}
 
-  # create directory structure
-  if ! mkdir "${INSTALL_DIR}"; then
-    log_crit "Directory ${INSTALL_DIR} exists. Moving"
-    # Create backup, moving older backup if need be
-    mv -n "${INSTALL_DIR}" "${INSTALL_DIR}-backup"
-  fi
-  log_info "Created directory ${INSTALL_DIR}"
+install_xcode_cli() {
+    if [ "$(uname)" = "Darwin" ]; then
+        if ! xcode-select --print-path &>/dev/null; then
+            echo "Xcode CLI tools not found. Installing them..."
+            xcode-select --install
+            echo "Please continue with the script after the installation is complete."
+            exit 1
+        fi
+    fi
+}
 
-  # git download
-  git clone --recurse-submodules ${GITHUB_DOWNLOAD} ${INSTALL_DIR}
+log_info() {
+	[ 2 -le "${LOG_LEVEL}" ] || return 0
+	echo info "$@" 1>&2
+}
 
-  # install
-  (${INSTALL_DIR}/install) || (log_crit "install failed" && exit 1)
-  log_info "Successfully installed."
+log_crit() {
+	[ 0 -le "${LOG_LEVEL}" ] || return 0
+	echo critical "$@" 1>&2
 }
 
 parse_args() {
-	while getopts "i:dh:" arg; do
+	while getopts "i:l:h" arg; do
 		case "${arg}" in
 		i) INSTALL_DIR="${OPTARG}" ;;
-		d) LOG_LEVEL=3 ;;
+                l)
+                   case ${OPTARG} in
+                     ''|*[!0-9]*) echo "Error: -l requires an integer argument" ; exit 1 ;;
+                     *) LOG_LEVEL=${OPTARG} ;;
+                   esac
+                   ;;
 		h | \?) usage "$0" ;;
 		*) return 1 ;;
 		esac
@@ -63,68 +79,32 @@ parse_args() {
 	EXECARGS="$*"
 }
 
-http_download_curl() {
-	local_file=$1
-	source_url=$2
-	header=$3
-	if [ -z "${header}" ]; then
-		code=$(curl -w '%{http_code}' -sL -o "${local_file}" "${source_url}")
-	else
-		code=$(curl -w '%{http_code}' -sL -H "${header}" -o "${local_file}" "${source_url}")
-	fi
-	if [ "${code}" != "200" ]; then
-		log_debug "http_download_curl received HTTP status ${code}"
-		return 1
-	fi
-	return 0
-}
+main() {
+  parse_args "$@"
+  install_xcode_cli
+  check_command git
 
-http_download_wget() {
-	local_file=$1
-	source_url=$2
-	header=$3
-	if [ -z "${header}" ]; then
-		wget -q -O "${local_file}" "${source_url}" || return 1
-	else
-		wget -q --header "${header}" -O "${local_file}" "${source_url}" || return 1
-	fi
-}
+  if [ "$(whoami)" = "root" ]; then
+    log_crit "Do not run as root. Install dotfiles for a specific user."
+    exit 1
+  fi
 
-http_download() {
-	log_debug "http_download $2"
-	if is_command curl; then
-		http_download_curl "$@" || return 1
-		return
-	elif is_command wget; then
-		http_download_wget "$@" || return 1
-		return
-	fi
-	log_crit "http_download unable to find wget or curl"
-	return 1
-}
+  if ! mkdir "${INSTALL_DIR}" &>/dev/null; then
+    log_info "Directory ${INSTALL_DIR} exists. Checking if proper dotfiles repo."
+    if ! check_repo "${INSTALL_DIR}" ; then
+      log_crit "Directory ${INSTALL_DIR} exists and is not a proper dotfiles repo. Moving."
+      mv -n "${INSTALL_DIR}" "${INSTALL_DIR}-backup"
+    elif ! git fetch --dry-run --quiet "${INSTALL_DIR}" &>/dev/null; then
+      log_info "Directory ${INSTALL_DIR} exists and is a proper dotfiles repo. Skipping."
+      exit 0
+    fi
+  else
+    log_info "Cloning dotfiles repo from ${GITHUB_DOWNLOAD}"
+    git clone --recurse-submodules ${GITHUB_DOWNLOAD} ${INSTALL_DIR}
+  fi
 
-is_command() {
-	command -v "$1" >/dev/null
-}
-
-log_debug() {
-	[ 3 -le "${LOG_LEVEL}" ] || return 0
-	echo debug "$@" 1>&2
-}
-
-log_info() {
-	[ 2 -le "${LOG_LEVEL}" ] || return 0
-	echo info "$@" 1>&2
-}
-
-log_err() {
-	[ 1 -le "${LOG_LEVEL}" ] || return 0
-	echo error "$@" 1>&2
-}
-
-log_crit() {
-	[ 0 -le "${LOG_LEVEL}" ] || return 0
-	echo critical "$@" 1>&2
+  (${INSTALL_DIR}/install) || (log_crit "Installation failed" && exit 1)
+  log_info "Successfully installed."
 }
 
 main "$@"
